--DROP TABLE decor_comment CASCADE CONSTRAINTS;
--DROP TABLE decor_order_details CASCADE CONSTRAINTS;
--DROP TABLE decor_orders CASCADE CONSTRAINTS;
--DROP TABLE decor_cart_item CASCADE CONSTRAINTS;
--DROP TABLE decor_cart CASCADE CONSTRAINTS;
--DROP TABLE decor_banner CASCADE CONSTRAINTS;
--DROP TABLE decor_product CASCADE CONSTRAINTS;
--DROP TABLE decor_category CASCADE CONSTRAINTS;
--DROP TABLE decor_user CASCADE CONSTRAINTS;

-- Bảng người dùng
CREATE TABLE decor_user (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100),
    email         VARCHAR2(100) UNIQUE,
    password      VARCHAR2(255),
    phone         VARCHAR2(20),
    address       VARCHAR2(255),
    role          VARCHAR2(20),
    status        NUMBER,                                -- 0: inactive, 1: active
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP
);

-- Bảng danh mục sản phẩm
CREATE TABLE decor_category (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          NVARCHAR2(100),
    description   NVARCHAR2(255),
    parent_id     NUMBER,
    status        NUMBER, 
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP
);

-- Bảng sản phẩm
CREATE TABLE decor_product (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(255),
    description   VARCHAR2(1000),
    price         NUMBER(10,2),
    sale_price    NUMBER(10,2),
    quantity      NUMBER,
    image_url     VARCHAR2(255),
    status        NUMBER,                                -- 0: inactive, 1: active, 2: out_of_stock
    category_id   NUMBER,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES decor_category(id)
);

-- Bảng banner trang chủ
CREATE TABLE decor_banner (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200),
    image VARCHAR2(200),
    priority NUMBER,
    status NUMBER,
    link VARCHAR2(500),
    position VARCHAR2(100)
);

-- Bảng giỏ hàng
CREATE TABLE decor_cart (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES decor_user(id)
);

-- Bảng item trong giỏ hàng
CREATE TABLE decor_cart_item (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id       NUMBER,
    product_id    NUMBER,
    quantity      NUMBER,
    price         NUMBER(10,2),
    FOREIGN KEY (cart_id) REFERENCES decor_cart(id),
    FOREIGN KEY (product_id) REFERENCES decor_product(id)
);

-- Bảng đơn hàng
CREATE TABLE decor_orders (
    id            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id       NUMBER,
    address       VARCHAR2(500),
    note          VARCHAR2(1000),
    payment_method VARCHAR2(50),
    order_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_status VARCHAR2(50),
    transaction_id VARCHAR2(100),
    status        VARCHAR2(20) DEFAULT 'PENDING',
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES decor_user(id)
);

-- Bảng chi tiết đơn hàng
CREATE TABLE decor_order_details (
    id            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id      NUMBER,
    product_id    NUMBER,
    quantity      NUMBER,
    price         NUMBER(10,2),
    CONSTRAINT fk_details_order FOREIGN KEY (order_id) REFERENCES decor_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_details_product FOREIGN KEY (product_id) REFERENCES decor_product(id)
);

-- Bảng bình luận
CREATE TABLE decor_comment (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER,
    product_id    NUMBER,
    content       NVARCHAR2(1000),
    status        NUMBER,                                -- 0: hidden, 1: visible, 2: reported
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES decor_user(id),
    FOREIGN KEY (product_id) REFERENCES decor_product(id)
);

COMMIT;
INSERT INTO decor_user (name, email, password, phone, address, role, status)
VALUES ('Admin1', 'admin1@gmail.com', '123456', '0987654321', '123 Admin Street, Hanoi', 'admin', 1);

INSERT INTO decor_user (name, email, password, phone, address, role, status)
VALUES ('truong', 'user@example.com', '123', '0123456789', '456 User Avenue, Hanoi', 'user', 1);
-- Truy vấn kiểm tra
SELECT * FROM decor_comment;
SELECT * FROM decor_order_details;